<?php
// templates/page-woopop-template.php

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Enqueue necessary scripts and styles.
function woopop_enqueue_template_assets() {
    wp_enqueue_style( 'woopop-public-css', WOOP_POP_PLUGIN_URL . 'assets/css/public.css', [], WOOP_POP_VERSION );
    wp_enqueue_script( 'woopop-public-js', WOOP_POP_PLUGIN_URL . 'assets/js/public.js', [ 'jquery' ], WOOP_POP_VERSION, true );
    wp_enqueue_style( 'font-awesome', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css', [], '6.4.0' );
}
add_action( 'wp_enqueue_scripts', 'woopop_enqueue_template_assets' );

global $post;
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php wp_head(); ?>
    <style>
        /* Hide the page title */
        .woopop-page-title {
            display: none;
        }
    </style>
</head>
<body <?php body_class(); ?>>
    <?php
    // Output the content generated by the [woopop] shortcode.
    echo do_shortcode( $post->post_content );
    ?>
    <?php wp_footer(); ?>
</body>
</html>
